default:
  tags:
    - stock #This tag is used to select a runner

stages:
  - build

before_script:
  - git clone https://gitlab.com/annealmd/stock_market

build:
  stage: build
  script: 
    - bash stock_market/hello.sh
